from pathlib import Path
import json,re,html,shutil
root=Path('/mnt/data/v25work')
base='https://www.materialyardage.com'

def make_page(title,desc,path,h1,intro,body,faqs,section):
    url=base+path
    graph={"@context":"https://schema.org","@graph":[{"@type":"Article","headline":title,"description":desc,"url":url,"dateModified":"2026-09-29","author":{"@type":"Organization","name":"MaterialYardage"},"publisher":{"@type":"Organization","name":"MaterialYardage"}}]}
    if faqs:
        graph["@graph"].append({"@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faqs]})
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="{url}">
<meta property="og:type" content="article"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{url}"><link rel="stylesheet" href="/assets/css/styles.css">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-08MTZ3F4Q1"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','G-08MTZ3F4Q1');</script>
<script type="application/ld+json">{json.dumps(graph,ensure_ascii=False,separators=(',',':'))}</script></head><body>
<header class="site-header"><div class="wrap header-inner"><a class="brand" href="/">Material<span>Yardage</span></a><nav class="nav" aria-label="Primary"><a href="/calculators">Calculators</a><a href="/guides/topsoil-depth-guide">Guides</a><a href="/reference/material-density-chart">Reference</a><a href="/about">About</a><a href="/methodology">Methodology</a><a href="/contact">Contact</a></nav></div></header>
<main><div class="wrap narrow"><div class="crumbs"><a href="/">Home</a> / <a href="/calculators">Calculators</a> / {html.escape(section)} / {html.escape(h1)}</div><span class="pill">Updated September 2026 · Free reference guide</span><h1 style="margin-top:.7rem">{html.escape(h1)}</h1><p class="lede">{html.escape(intro)}</p>{body}</div></main>
<footer class="site-footer"><div class="wrap"><nav class="footer-nav" aria-label="Footer"><a href="/">Home</a><a href="/calculators">Calculators</a><a href="/guides/topsoil-depth-guide">Guides</a><a href="/reference/material-density-chart">Reference</a><a href="/about">About</a><a href="/methodology">Methodology</a><a href="/contact">Contact</a><a href="/privacy-policy">Privacy Policy</a></nav><p>© <span id="year">2026</span> MaterialYardage. Calculation estimates are provided for planning purposes.</p></div></footer><script src="/assets/js/main.js"></script></body></html>'''

pages=[]
def add(rel,title,desc,h1,intro,body,faqs,section='Guides'):
    pages.append((rel,make_page(title,desc,'/'+rel[:-5],h1,intro,body,faqs,section)))

add('guides/topsoil-depth-guide.html','Topsoil Depth Guide: How Deep Should Topsoil Be? | MaterialYardage','Practical topsoil depth ranges for lawns, planting beds, raised beds and lawn top-dressing, plus a volume example and ordering tips.','Topsoil Depth Guide: How Deep Should Topsoil Be?','The right topsoil depth depends on what you are building. Use these ranges as planning guidance, then calculate the volume with the Topsoil Calculator.','''<section class="block"><h2>Typical topsoil depths</h2><div class="table-scroll"><table><thead><tr><th>Project</th><th>Typical depth</th><th>Planning note</th></tr></thead><tbody><tr><td>Existing lawn top-dressing</td><td>¼–½ in</td><td>Use a thin, even layer so existing grass remains exposed.</td></tr><tr><td>New lawn / turf preparation</td><td>4–6 in</td><td>Use enough quality soil to establish a workable root zone.</td></tr><tr><td>Flower and planting beds</td><td>6–12 in</td><td>Depth varies with existing soil and the plants being installed.</td></tr><tr><td>Vegetable / raised beds</td><td>8–12 in+</td><td>Deeper beds may suit crops with larger root systems.</td></tr></tbody></table></div></section><section class="block"><h2>How depth changes quantity</h2><p>Multiply length and width in feet by depth in feet, then divide cubic feet by 27.</p><div class="formula">Cubic feet = length × width × (depth in ÷ 12)<br>Cubic yards = cubic feet ÷ 27</div><p>Example: 20 ft × 10 ft × 6 in = 100 ft³ = about 3.70 yd³ before any allowance.</p></section><section class="block"><h2>Ordering allowance</h2><p>Loose soil can settle after spreading and watering. A planning allowance of roughly 5–10% can help with settling and uneven areas, but it should not replace site measurements or supplier advice.</p></section><section class="block"><h2>Related tools</h2><ul><li><a href="/">Topsoil Calculator</a></li><li><a href="/landscaping/compost-mix">Compost &amp; Soil Mix Calculator</a></li><li><a href="/reference/material-density-chart">Material Density Chart</a></li></ul></section>''',[('How deep should topsoil be for a new lawn?','A common planning range is about 4 to 6 inches, subject to the site, existing soil and turf requirements.'),('How deep should topsoil be in a planting bed?','About 6 to 12 inches is a common planning range, but plant type and existing soil conditions can change the requirement.'),('Should I add extra topsoil for settling?','A modest 5–10% planning allowance can help with settling and uneven areas, but supplier and site conditions should guide the final order.')])

add('guides/mulch-depth-guide.html','Mulch Depth Guide: How Many Inches of Mulch Do You Need? | MaterialYardage','Compare common mulch depths, calculate cubic yards and understand how depth changes material quantity.','Mulch Depth Guide: How Many Inches of Mulch Do You Need?','Mulch depth controls coverage and material cost. Use these planning ranges and the formula below to estimate bulk volume.','''<section class="block"><h2>Common mulch depth ranges</h2><div class="table-scroll"><table><thead><tr><th>Use</th><th>Typical depth</th><th>Planning note</th></tr></thead><tbody><tr><td>Light refresh</td><td>1–2 in</td><td>Useful where an existing mulch layer remains.</td></tr><tr><td>General landscape beds</td><td>2–3 in</td><td>A common range for a new or refreshed layer.</td></tr><tr><td>Deeper organic layer</td><td>3–4 in</td><td>Use care around stems and trunks.</td></tr></tbody></table></div></section><section class="block"><h2>Mulch quantity formula</h2><div class="formula">Cubic yards = length (ft) × width (ft) × depth (in) ÷ 12 ÷ 27</div><p>For irregular beds, split the space into rectangles or other simple sections and add the results.</p></section><section class="block"><h2>Bulk vs bags</h2><p>Bulk mulch is usually quoted by cubic yard while retail mulch is sold by bag volume. Check the actual bag volume printed on the package before converting.</p></section><section class="block"><h2>Related tools</h2><ul><li><a href="/mulch-calculator">Mulch Calculator</a></li><li><a href="/landscaping/mulch">Mulch Coverage Matrix</a></li><li><a href="/reference/coverage-tables">Coverage Tables</a></li></ul></section>''',[('How deep should mulch be?','A 2–3 inch layer is a common planning range for landscape beds. Avoid piling mulch against plant stems or tree trunks.'),('How many cubic yards of mulch do I need?','Multiply length by width by depth in inches, convert depth to feet and divide cubic feet by 27.'),('Should mulch touch tree trunks?','Avoid creating a deep mulch mound against trunks or stems; keep the immediate base clear enough to avoid persistent moisture against bark.')])

add('guides/gravel-driveway-guide.html','Gravel Driveway Calculator Guide: Depth, Volume and Ordering | MaterialYardage','Learn how to estimate gravel for a driveway, plan layer volumes and convert cubic yards to approximate tons.','Gravel Driveway Guide: Depth, Volume and Ordering','Gravel driveways are often built in layers. Quantity depends on driveway area, the depth of each layer and aggregate density.','''<section class="block"><h2>Measure the driveway</h2><p>Multiply length by width for a rectangular driveway. For curves or widening sections, divide the driveway into simple shapes and add their areas.</p><div class="formula">Cubic feet = area (ft²) × depth (in) ÷ 12<br>Cubic yards = cubic feet ÷ 27</div></section><section class="block"><h2>Plan each layer separately</h2><p>Sub-base, intermediate aggregate and surface gravel can have different functions. Estimate each layer independently rather than treating the whole driveway as one material.</p><p>For heavy traffic, weak subgrade or drainage-sensitive sites, follow the project specification or local engineering guidance for layer thickness and material type.</p></section><section class="block"><h2>Convert volume to tons</h2><p>Multiply cubic yards by a density expressed in tons per cubic yard. Moisture, grading and compaction change delivered weight, so supplier-specific density is preferable.</p></section><section class="block"><h2>Related tools</h2><ul><li><a href="/gravel-calculator">Gravel Calculator</a></li><li><a href="/landscaping/gravel">Gravel &amp; Road Base Calculator</a></li><li><a href="/reference/material-density-chart">Material Density Chart</a></li><li><a href="/reference/coverage-tables">Coverage Tables</a></li></ul></section>''',[('How deep should a gravel driveway be?','Depth depends on subgrade, drainage, traffic and the specified layer structure. Estimate each layer separately and follow project requirements.'),('How do I calculate tons of gravel?','Calculate cubic yards first, then multiply by the applicable tons-per-cubic-yard density.'),('Should a gravel driveway have multiple layers?','Many driveway designs use more than one aggregate layer so the base and surface perform different functions; the exact design depends on site and traffic.')])

add('guides/concrete-calculator-guide.html','Concrete Calculator Guide: Slabs, Footings and Waste Allowance | MaterialYardage','Learn how to estimate concrete volume for rectangular slabs and similar pours, convert cubic feet to yards and account for ordering allowance.','Concrete Calculator Guide: Volume, Depth and Ordering','Concrete quantity is fundamentally a volume calculation. Accurate measurement and a visible ordering allowance are the key planning steps.','''<section class="block"><h2>Basic concrete volume</h2><p>Convert length, width and thickness to consistent units, multiply them, then convert cubic feet to cubic yards.</p><div class="formula">Cubic feet = length (ft) × width (ft) × thickness (ft)<br>Cubic yards = cubic feet ÷ 27</div><p>If thickness is in inches, divide it by 12 first.</p></section><section class="block"><h2>Worked example</h2><div class="example"><p><strong>Slab:</strong> 20 ft × 10 ft × 4 in</p><p>Thickness = 4 ÷ 12 = 0.333 ft.</p><p>Volume ≈ 20 × 10 × 0.333 = 66.67 ft³.</p><p>Volume ≈ 2.47 yd³ before an ordering allowance.</p></div></section><section class="block"><h2>Structural limitation</h2><p>This is a quantity calculator, not a structural concrete design tool. Strength class, reinforcement, exposure, water-cement ratio, aggregate grading and placement requirements should follow the project specification or qualified professional.</p></section><section class="block"><h2>Related tools</h2><ul><li><a href="/concrete/calculator">Concrete Calculator</a></li><li><a href="/concrete/slab">Concrete Slab Calculator</a></li><li><a href="/concrete/mix-proportions">Concrete Mix Proportions</a></li><li><a href="/materials/material-cost">Material Cost Calculator</a></li></ul></section>''',[('How do I calculate concrete for a slab?','Multiply slab length, width and thickness using consistent units, then divide cubic feet by 27 to get cubic yards.'),('How much extra concrete should I order?','A planning allowance can cover measurement and placement losses, but the appropriate allowance depends on the project and supplier.'),('Does this calculator design concrete strength?','No. It estimates quantity only. Structural mix design and reinforcement should follow project specifications and applicable standards.')])

add('guides/paver-calculator-guide.html','Paver Calculator Guide: Patio Area, Paver Count and Waste | MaterialYardage','Learn how to calculate paver quantities from patio area, paver dimensions and cutting waste, with a worked calculation method.','Paver Calculator Guide: Area, Quantity and Waste','Paver quantity starts with finished surface area and the face area of one paver. The final order should include a cutting and breakage allowance appropriate to the pattern.','''<section class="block"><h2>Calculate the surface area</h2><p>For a rectangular patio, multiply length by width. For an irregular patio, split it into simple shapes and add their areas.</p></section><section class="block"><h2>Calculate paver count</h2><p>Use consistent units for the patio and paver dimensions. Divide project area by the face area of one paver, then apply a waste allowance.</p><div class="formula">Pavers required ≈ project area ÷ one-paver face area<br>Order quantity = required pavers × (1 + waste allowance)</div></section><section class="block"><h2>Waste depends on pattern</h2><p>Running bond, diagonal, herringbone and border layouts can have very different cutting requirements. More complex patterns generally need more planning allowance.</p></section><section class="block"><h2>Other materials</h2><p>Paver count does not automatically determine bedding sand, jointing material, base aggregate or edge restraint. Calculate those separately from the project design.</p></section><section class="block"><h2>Related tools</h2><ul><li><a href="/paving/paver">Paver Calculator</a></li><li><a href="/reference/conversion-tables">Conversion Tables</a></li><li><a href="/materials/material-cost">Material Cost Calculator</a></li></ul></section>''',[('How do I calculate how many pavers I need?','Calculate finished area, divide by the face area of one paver using consistent units, then add an allowance for cuts and breakage.'),('How much paver waste should I allow?','The allowance depends on the laying pattern, borders, cuts and material. Complex layouts generally need more allowance.'),('Does paver quantity include sand and base material?','No. Pavers, bedding material, jointing material and base aggregate are separate quantities.')])

add('reference/material-density-chart.html','Material Density Chart: Tons per Cubic Yard | MaterialYardage','Approximate material density reference for topsoil, mulch, gravel and aggregates. Use supplier-specific density when available.','Material Density Chart: Approximate Tons per Cubic Yard','Density converts a volume estimate into an approximate weight. Actual bulk density varies with moisture, grading, compaction and composition.','''<section class="block"><h2>Approximate bulk density</h2><div class="table-scroll"><table><thead><tr><th>Material</th><th>Approx. tons/yd³</th></tr></thead><tbody><tr><td>Unscreened topsoil</td><td>1.10</td></tr><tr><td>Screened topsoil</td><td>1.00</td></tr><tr><td>Garden soil / blend</td><td>0.90</td></tr><tr><td>Compost</td><td>0.60</td></tr><tr><td>Shredded bark mulch</td><td>0.40</td></tr><tr><td>Wood chip mulch</td><td>0.45</td></tr><tr><td>Pine straw / bark nuggets</td><td>0.30</td></tr><tr><td>Rubber mulch</td><td>0.60</td></tr><tr><td>Pea gravel</td><td>1.35</td></tr><tr><td>River rock</td><td>1.35</td></tr><tr><td>Crushed stone</td><td>1.40</td></tr><tr><td>Crusher run / road base</td><td>1.50</td></tr><tr><td>Decomposed granite</td><td>1.30</td></tr></tbody></table></div></section><section class="block"><h2>Use the density</h2><div class="formula">Estimated tons = cubic yards × tons per cubic yard</div><p>For example, 5 yd³ at 1.40 tons/yd³ gives an estimate of 7.0 tons. This is a planning calculation, not a certified shipment weight.</p></section><section class="block"><h2>Why density varies</h2><p>Moisture, particle size, void space, organic content and compaction can change bulk density. For delivery and freight planning, use supplier data whenever possible.</p></section><section class="block"><h2>Related calculators</h2><ul><li><a href="/gravel-calculator">Gravel Calculator</a></li><li><a href="/">Topsoil Calculator</a></li><li><a href="/mulch-calculator">Mulch Calculator</a></li><li><a href="/materials/sand">Sand Calculator</a></li><li><a href="/materials/aggregate">Aggregate Calculator</a></li></ul></section>''',[('Are these material densities exact?','No. They are approximate planning values. Moisture, grading, composition and compaction can materially change bulk density.'),('How do I convert cubic yards to tons?','Multiply cubic yards by the applicable tons-per-cubic-yard density. Use supplier-specific density when available.'),('Why can wet soil weigh more than dry soil?','Water adds mass and changes bulk density, so the same nominal volume can have a different delivered weight.')],'Reference')

add('reference/conversion-tables.html','Construction Material Conversion Tables | Cubic Yards, Feet, Meters and Tons | MaterialYardage','Quick reference for cubic feet, cubic yards, cubic meters, inches, feet, meters and area conversions.','Construction Material Conversion Tables','Use these conversions when a supplier quote, calculator or drawing uses different units from your measurements.','''<section class="block"><h2>Volume conversions</h2><div class="table-scroll"><table><thead><tr><th>From</th><th>Equivalent</th></tr></thead><tbody><tr><td>1 cubic yard</td><td>27 cubic feet</td></tr><tr><td>1 cubic yard</td><td>0.7646 cubic meters</td></tr><tr><td>1 cubic meter</td><td>35.3147 cubic feet</td></tr><tr><td>1 cubic meter</td><td>1.30795 cubic yards</td></tr></tbody></table></div></section><section class="block"><h2>Length and depth</h2><div class="table-scroll"><table><thead><tr><th>From</th><th>Equivalent</th></tr></thead><tbody><tr><td>12 inches</td><td>1 foot</td></tr><tr><td>1 foot</td><td>0.3048 meter</td></tr><tr><td>1 meter</td><td>3.28084 feet</td></tr><tr><td>1 centimeter</td><td>0.3937 inch</td></tr></tbody></table></div></section><section class="block"><h2>Useful formulas</h2><div class="formula">Cubic yards = cubic feet ÷ 27<br>Cubic meters = cubic feet ÷ 35.3147<br>Cubic feet = cubic yards × 27</div><p>For material weight, multiply volume by an appropriate density. Do not use a generic density for a supplier-certified load.</p></section><section class="block"><h2>Area conversions</h2><div class="table-scroll"><table><thead><tr><th>From</th><th>Equivalent</th></tr></thead><tbody><tr><td>1 square meter</td><td>10.7639 square feet</td></tr><tr><td>1 square foot</td><td>0.092903 square meter</td></tr></tbody></table></div></section><section class="block"><h2>Related tools</h2><ul><li><a href="/calculators">All Calculators</a></li><li><a href="/reference/material-density-chart">Material Density Chart</a></li><li><a href="/reference/coverage-tables">Coverage Tables</a></li></ul></section>''',[('How many cubic feet are in a cubic yard?','There are exactly 27 cubic feet in one cubic yard.'),('How many cubic yards are in a cubic meter?','One cubic meter is approximately 1.30795 cubic yards.'),('How many feet are in a meter?','One meter equals exactly 3.28084 feet.')],'Reference')

add('reference/coverage-tables.html','Material Coverage Tables: Topsoil, Mulch and Gravel | MaterialYardage','Quick coverage references showing how many square feet one cubic yard covers at common depths.','Material Coverage Tables','Coverage is controlled by depth. These tables help you sanity-check a calculator result before ordering.','''<section class="block"><h2>Square feet covered by 1 cubic yard</h2><div class="table-scroll"><table><thead><tr><th>Depth</th><th>Coverage</th></tr></thead><tbody><tr><td>1 inch</td><td>324 ft²</td></tr><tr><td>2 inches</td><td>162 ft²</td></tr><tr><td>3 inches</td><td>108 ft²</td></tr><tr><td>4 inches</td><td>81 ft²</td></tr><tr><td>6 inches</td><td>54 ft²</td></tr><tr><td>8 inches</td><td>40.5 ft²</td></tr><tr><td>12 inches</td><td>27 ft²</td></tr></tbody></table></div><p>These are mathematical volume relationships before settling, compaction or installation losses.</p></section><section class="block"><h2>How coverage is calculated</h2><div class="formula">Coverage (ft²) = 27 ÷ depth (ft)</div><p>At 3 inches, depth is 0.25 ft, so one cubic yard covers 27 ÷ 0.25 = 108 ft².</p></section><section class="block"><h2>Bagged material</h2><p>Bag coverage depends on the volume printed on the bag. A 2 ft³ bag at 3 inches deep covers about 8 ft² before settling and installation losses.</p></section><section class="block"><h2>Related calculators</h2><ul><li><a href="/">Topsoil Calculator</a></li><li><a href="/mulch-calculator">Mulch Calculator</a></li><li><a href="/gravel-calculator">Gravel Calculator</a></li><li><a href="/reference/material-density-chart">Material Density Chart</a></li></ul></section>''',[('How much area does one cubic yard cover?','It depends on depth. At 3 inches, one cubic yard mathematically covers 108 square feet; at 6 inches, it covers 54 square feet.'),('Does one cubic yard always cover the same area?','No. Coverage changes directly with installation depth and real-world settling.'),('How much does a 2 cubic foot bag cover?','At 3 inches deep, a 2 cubic foot bag covers about 8 square feet before settling or installation losses.')],'Reference')

for rel,content in pages:
    p=root/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content,encoding='utf-8')

# standardize nav/footer sitewide, excluding 404
for p in root.rglob('*.html'):
    if p.name=='404.html': continue
    s=p.read_text(encoding='utf-8')
    s=re.sub(r'<nav class="nav"[^>]*>.*?</nav>','<nav class="nav" aria-label="Primary"><a href="/calculators">Calculators</a><a href="/guides/topsoil-depth-guide">Guides</a><a href="/reference/material-density-chart">Reference</a><a href="/about">About</a><a href="/methodology">Methodology</a><a href="/contact">Contact</a></nav>',s,count=1,flags=re.S)
    s=re.sub(r'<nav class="footer-nav"[^>]*>.*?</nav>','<nav class="footer-nav" aria-label="Footer"><a href="/">Home</a><a href="/calculators">Calculators</a><a href="/guides/topsoil-depth-guide">Guides</a><a href="/reference/material-density-chart">Reference</a><a href="/about">About</a><a href="/methodology">Methodology</a><a href="/contact">Contact</a><a href="/privacy-policy">Privacy Policy</a></nav>',s,count=1,flags=re.S)
    p.write_text(s,encoding='utf-8')

# add guide/reference blocks to calculator hub
p=root/'calculators.html';s=p.read_text(encoding='utf-8')
marker='<section class="block"><h2>Before you order</h2>'
if 'Planning guides' not in s:
    block='''<section class="block"><h2>Planning guides</h2><ul class="cards three"><li><a href="/guides/topsoil-depth-guide"><strong>Topsoil Depth Guide</strong><span>Practical depths and cubic-yard examples.</span></a></li><li><a href="/guides/mulch-depth-guide"><strong>Mulch Depth Guide</strong><span>Depth, bulk volume and bag coverage.</span></a></li><li><a href="/guides/gravel-driveway-guide"><strong>Gravel Driveway Guide</strong><span>Layer planning, volume and tonnage.</span></a></li><li><a href="/guides/concrete-calculator-guide"><strong>Concrete Calculator Guide</strong><span>Slab volume and ordering allowances.</span></a></li><li><a href="/guides/paver-calculator-guide"><strong>Paver Calculator Guide</strong><span>Area, paver count and cutting waste.</span></a></li></ul></section><section class="block"><h2>Reference tables</h2><ul class="cards three"><li><a href="/reference/material-density-chart"><strong>Material Density Chart</strong><span>Approximate tons per cubic yard.</span></a></li><li><a href="/reference/conversion-tables"><strong>Conversion Tables</strong><span>Volume, length and area conversions.</span></a></li><li><a href="/reference/coverage-tables"><strong>Coverage Tables</strong><span>Area coverage at common depths.</span></a></li></ul></section>'''
    s=s.replace(marker,block+marker)
p.write_text(s,encoding='utf-8')

# homepage contextual link
p=root/'index.html';s=p.read_text(encoding='utf-8')
marker='  <section class="block">\n    <h2>How the cubic yard calculation works</h2>'
if 'Topsoil planning guides' not in s and marker in s:
    s=s.replace(marker,'  <section class="block"><h2>Topsoil planning guides</h2><p>Use the <a href="/guides/topsoil-depth-guide">topsoil depth guide</a> for practical depth ranges, and the <a href="/reference/material-density-chart">material density chart</a> when converting volume to approximate weight.</p></section>\n\n'+marker)
p.write_text(s,encoding='utf-8')

# sitemap
urls=[]
for p in root.rglob('*.html'):
    if p.name=='404.html' or 'assets' in p.parts: continue
    rel=p.relative_to(root).as_posix(); u='/' if rel=='index.html' else '/'+rel[:-5];urls.append(u)
urls=sorted(set(urls),key=lambda x:(x!='/',x))
pri={'/':'1.0','/calculators':'0.9','/mulch-calculator':'0.9','/gravel-calculator':'0.9'}
for u in urls:
    if u.startswith('/guides/') or u.startswith('/reference/'): pri[u]='0.8'
    elif u in ['/about','/methodology']: pri[u]='0.6'
    elif u=='/contact':pri[u]='0.5'
    elif u=='/privacy-policy':pri[u]='0.3'
lines=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
for u in urls:
    freq='weekly' if u in ['/','/mulch-calculator','/gravel-calculator'] else 'monthly'
    lines.append(f'<url><loc>{base}{u}</loc><lastmod>2026-09-29</lastmod><changefreq>{freq}</changefreq><priority>{pri.get(u,"0.7")}</priority></url>')
lines.append('</urlset>');(root/'sitemap.xml').write_text('\n'.join(lines)+'\n',encoding='utf-8')

(root/'SEO-CONTENT-REPORT-v2.5.md').write_text(f'''# MaterialYardage v2.5 — SEO / Content Expansion\n\nDate: 2026-09-29\n\n## New guides\n- /guides/topsoil-depth-guide\n- /guides/mulch-depth-guide\n- /guides/gravel-driveway-guide\n- /guides/concrete-calculator-guide\n- /guides/paver-calculator-guide\n\n## New reference resources\n- /reference/material-density-chart\n- /reference/conversion-tables\n- /reference/coverage-tables\n\n## Sitewide improvements\n- Guides and Reference links added to primary and footer navigation.\n- Calculator directory expanded with editorial guides and reference tables.\n- Topsoil page linked to its new depth guide and density reference.\n- Sitemap rebuilt using clean URLs.\n- New editorial pages include Article and FAQ structured data.\n- New pages are designed to provide formulas, examples, assumptions and limitations rather than thin keyword content.\n\nSitemap URL count: {len(urls)}\n''',encoding='utf-8')
print('created',len(pages),'new pages; sitemap',len(urls))
